<?php
require __DIR__ . '/Printer.php';

$ip = '192.168.0.11';
$port = '9100';

$printer = new Printer($ip, $port);
/**
 * 开始测试一个基本的打印
 */
$printer->fontBold()
        ->fontSize("\x11")
        ->write($printer->vs("纯K 江北店"))
        ->align(Printer::ALIGN_RIGHT)
    ->print()
    ->line()
        ->align(Printer::ALIGN_LEFT)
        ->fontSize("\x11")
        ->write($printer->sr(Printer::W1,"大包A100(5人)"))
        ->fontSize("\x00")
        ->write($printer->vs("结帐"))
    ->print()
        ->fontBold()
        ->write($printer->vs("单号：12323243243243"))
        ->fontUnbold()
    ->print()->print()
        ->write($printer->sr(Printer::W5, "房型：豪中"))
        ->write($printer->vs("收银台：前台预订"))
    ->print()
        ->write($printer->sr(Printer::W5, "计费方式：分钟计时"))
        ->write($printer->vs("收银员：hahayoung"))
    ->print()
        ->write($printer->vs("进场时间：15:33"))
    ->print()
        ->write($printer->vs("离场时间：23:00"))
    ->print()
    ->line()
        ->write($printer->sr(Printer::W4, "时段"))
        ->write($printer->sr(Printer::W5, "消费时间"))
        ->write($printer->sr(Printer::W1, "小计"))
    ->print()
    ->line()
        ->write($printer->sr(Printer::W4, "（原价￥48/H）"))
        ->write($printer->sr(Printer::W5, "10:11-11:11 15分钟"))
        ->write($printer->sr(Printer::W1, "123.32"))
    ->print()
        ->write($printer->sr(Printer::W4, "（原价￥48/H）"))
        ->write($printer->sr(Printer::W5, "10:11-11:11 15分钟"))
        ->write($printer->sr(Printer::W1, "123.32"))
    ->print()
        ->write($printer->sr(Printer::W4, "（原价￥48/H）"))
        ->write($printer->sr(Printer::W5, "10:11-11:11 15分钟"))
        ->write($printer->sr(Printer::W1, "123.32"))
    ->print()
        ->write($printer->sr(Printer::W4, "（原价￥48/H）"))
        ->write($printer->sr(Printer::W5, "10:11-11:11 15分钟"))
        ->write($printer->sr(Printer::W1, "123.32"))
    ->print()->print()
        ->write($printer->vs("换/拼房记录"))
    ->print()    
        ->write($printer->sr(Printer::W2, "放号"))
        ->write($printer->sr(Printer::W5, "时间"))
        ->write($printer->sr(Printer::W2, "费用"))
        ->write($printer->sr(Printer::W1, "备注"))
    ->print()
        ->write($printer->sr(Printer::W2, "A23"))
        ->write($printer->sr(Printer::W5, "[1-12 11:00->1-12 12:00]"))
        ->write($printer->sr(Printer::W2, "12.00"))
        ->write($printer->sr(Printer::W1, "换"))
    ->print()
        ->write($printer->sr(Printer::W2, "A23"))
        ->write($printer->sr(Printer::W5, "[1-12 11:00->1-12 12:00]"))
        ->write($printer->sr(Printer::W2, "12.00"))
        ->write($printer->sr(Printer::W1, "换"))
    ->print()
        ->write($printer->sr(Printer::W2, "A23"))
        ->write($printer->sr(Printer::W5, "[1-12 11:00->1-12 12:00]"))
        ->write($printer->sr(Printer::W2, "12.00"))
        ->write($printer->sr(Printer::W1, "换"))
    ->print()->cut();

